### ISSUE TITLE
SketchGAN pre-train model

### ISSUE THREAD

**Issue by wangqiang9** [wchen342/android-rebuilds#1]
Thank you for your outstanding contribution! We have tried many ways to download your augmented dataset, but failed. I ask you to share your Pretrain model and pay tribute to your seriousness and patience. My email is wanqqiang@bupt.edu.cn

**Comment by wchen342** [comment]
I no longer have the dataset. You can try crawling your own images with their API.
Also please do not open issues in unrelated repo.
